const promptsData = [
    {
        title: "🎯 Estrategia y Nicho",
        color: "bg-blue-600",
        iconName: "Target",
        subcategories: [
            {
                title: "Definición de Negocio",
                prompts: [
                    { id: 1, title: "Análisis de Sub-nichos", prompt: "Actúa como un consultor de estrategia de negocios. Analiza mi nicho actual '[Mi Nicho]' y mi servicio principal '[Mi Servicio]'. Identifica 3 sub-nichos de alta rentabilidad y baja competencia. Para cada sub-nicho, define el 'Problema Principal' que resuelvo, el 'Valor Único' de mi oferta y un 'Titular de Posicionamiento' de 10 palabras. Presenta la salida en una tabla Markdown con las columnas: Sub-Nicho, Problema Principal, Valor Único, Titular de Posicionamiento.", cuandoUsar: "Inicio o Pivote", tiempoEstimado: "30 min" },
                    { id: 2, title: "Análisis de Riesgos", prompt: "Asume el rol de un analista de riesgos. Evalúa la sostenibilidad a largo plazo de mi modelo de negocio freelance basado en '[Mi Modelo de Ingresos, ej: por proyecto, por retainer]'. Identifica 5 riesgos clave (ej: dependencia de un cliente, saturación del mercado) y sugiere una estrategia de mitigación para cada uno. Formato de salida: Lista numerada de Riesgo y Estrategia de Mitigación.", cuandoUsar: "Evaluación anual", tiempoEstimado: "45 min" },
                    { id: 3, title: "Estrategia Océano Azul", prompt: "Eres un experto en 'Blue Ocean Strategy'. Dame 3 ideas para diferenciar mi servicio de '[Mi Servicio]' de la competencia, creando un nuevo espacio de mercado. Las ideas deben enfocarse en la eliminación, reducción, aumento y creación de factores de valor (Framework E-R-A-C). Presenta la respuesta siguiendo el formato del framework E-R-A-C para cada idea.", cuandoUsar: "Diferenciación", tiempoEstimado: "60 min" },
                    { id: 4, title: "Buyer Persona Ideal", prompt: "Define mi 'Cliente Ideal' (Buyer Persona) para mi servicio de '[Mi Servicio]' con un alto poder adquisitivo. Incluye: Nombre, Edad, Puesto, Ingreso Estimado, 3 Puntos de Dolor (Pain Points) relacionados con mi servicio, 3 Objetivos (Goals) y 2 Canales de Comunicación preferidos. Formato de salida: Ficha de Buyer Persona estructurada.", cuandoUsar: "Marketing", tiempoEstimado: "30 min" },
                    { id: 5, title: "Diseño Funnel de Ventas", prompt: "Diseña un 'Funnel de Ventas' de 5 etapas (Conciencia, Interés, Consideración, Intención, Compra) para mi servicio de '[Mi Servicio]'. Para cada etapa, especifica el 'Contenido Clave' a crear y la 'Métrica de Éxito' a medir. Formato de salida: Tabla Markdown.", cuandoUsar: "Estrategia Ventas", tiempoEstimado: "45 min" },
                    { id: 6, title: "Jobs To Be Done (JTBD)", prompt: "Utiliza el framework 'Jobs To Be Done' (JTBD). Describe el 'Trabajo' que mi cliente está tratando de hacer cuando me contrata para '[Mi Servicio]'. Identifica las 'Fuerzas de Progreso' y las 'Fuerzas de Ansiedad' que influyen en su decisión. Concluye con una 'Declaración de JTBD' completa. Formato de salida: Texto estructurado con subtítulos.", cuandoUsar: "Copywriting", tiempoEstimado: "40 min" },
                    { id: 7, title: "Estructura de Precios", prompt: "Actúa como un estratega de precios. Propón 3 estructuras de precios para mi servicio de '[Mi Servicio]' (ej: Precio Fijo, Tarifa por Hora, Precio Basado en Valor). Para cada estructura, justifica por qué es adecuada para un freelancer de nivel medio-alto. Formato de salida: Lista numerada con Estructura de Precio y Justificación.", cuandoUsar: "Cotización", tiempoEstimado: "30 min" },
                    { id: 8, title: "Plan de Referidos 90 Días", prompt: "Soy un freelancer de '[Mi Área]'. Genera un plan de 90 días enfocado en la 'Adquisición de Clientes por Referencia'. El plan debe incluir 3 acciones específicas por mes (9 en total) y un 'Script de Solicitud de Referencia' que pueda usar con clientes satisfechos. Formato de salida: Plan de 90 días (Mes 1, Mes 2, Mes 3) y Script.", cuandoUsar: "Crecimiento", tiempoEstimado: "30 min" },
                    { id: 9, title: "Producto Tripwire", prompt: "Analiza el concepto de 'Producto Digital de Bajo Costo' (Tripwire) que puedo crear para complementar mi servicio principal de '[Mi Servicio]'. Propón 3 ideas de productos digitales (ej: plantilla, checklist, mini-curso) y el 'Precio de Entrada' sugerido. Formato de salida: Lista numerada de Idea de Producto y Precio de Entrada.", cuandoUsar: "Ingresos Pasivos", tiempoEstimado: "45 min" },
                    { id: 10, title: "Misión y Visión", prompt: "Escribe una 'Declaración de Misión' y una 'Declaración de Visión' de alto impacto para mi marca personal como freelancer. La misión debe enfocarse en el 'Impacto' que genero en mis clientes, y la visión en el 'Futuro' que aspiro a crear. Ambas deben ser concisas (máximo 20 palabras). Formato de salida: Misión y Visión claramente etiquetadas.", cuandoUsar: "Branding", tiempoEstimado: "20 min" }
                ]
            }
        ]
    },
    {
        title: "✍️ Contenido y Marketing",
        color: "bg-purple-600",
        iconName: "PenTool",
        subcategories: [
            {
                title: "Creación de Contenido",
                prompts: [
                    { id: 11, title: "Estructura Artículo Pilar", prompt: "Actúa como un 'Especialista en SEO y Escritura Persuasiva'. Dame una estructura detallada para un 'Artículo Pilar' (Pillar Content) de 3000 palabras sobre '[Mi Tema Clave]'. La estructura debe incluir: Título H1 optimizado, 5 Subtítulos H2 (con intención de búsqueda clara), 15 Subtítulos H3 (para profundidad), y una 'Conclusión con Llamada a la Acción' (CTA) para mi servicio de '[Mi Servicio]'. Formato de salida: Esquema jerárquico (H1, H2, H3).", cuandoUsar: "SEO Blog", tiempoEstimado: "60 min" },
                    { id: 12, title: "Copy Anuncios LinkedIn", prompt: "Eres un experto en 'Copywriting AIDA' (Atención, Interés, Deseo, Acción). Redacta 5 variaciones de 'Copy para Anuncios de LinkedIn' para promocionar mi servicio de '[Mi Servicio]' a mi Buyer Persona (definido en el prompt 4). Cada variación debe tener un máximo de 280 caracteres y enfocarse en un 'Punto de Dolor' diferente. Formato de salida: Lista numerada de 5 copys.", cuandoUsar: "Publicidad", tiempoEstimado: "30 min" },
                    { id: 13, title: "Contenido Evergreen", prompt: "Diseña una 'Estrategia de Contenido Evergreen' para mi blog. Identifica 10 temas que resuelvan dudas fundamentales sobre '[Mi Área de Experiencia]' y que tengan un potencial de tráfico constante. Para cada tema, sugiere un 'Formato de Contenido' (ej: Guía, Tutorial, Checklist) y la 'Palabra Clave Principal' a atacar. Formato de salida: Tabla Markdown.", cuandoUsar: "Planificación", tiempoEstimado: "45 min" },
                    { id: 14, title: "Reescritura StoryBrand", prompt: "Analiza el siguiente texto de mi página 'Acerca de Mí' y reescríbelo utilizando el 'Framework StoryBrand' (Héroe, Guía, Plan, Llamada a la Acción, Éxito, Fracaso). El cliente debe ser el 'Héroe' y yo el 'Guía'. Texto a reescribir: '[Mi Texto Actual]'. Formato de salida: Texto reescrito con anotaciones de StoryBrand.", cuandoUsar: "Web Copy", tiempoEstimado: "40 min" },
                    { id: 15, title: "Titulares Clickbait Éticos", prompt: "Genera 10 ideas de 'Titulares Clickbait Éticos' para un video de YouTube sobre '[Mi Tema]'. Los titulares deben ser emocionalmente resonantes, generar curiosidad y ser honestos sobre el contenido. Utiliza el formato de lista numerada.", cuandoUsar: "YouTube/Blog", tiempoEstimado: "20 min" },
                    { id: 16, title: "Optimización Email Ventas", prompt: "Actúa como un 'Editor de Contenido'. Revisa el siguiente borrador de email de venta y optimízalo para 'Claridad, Concisión y Persuasión'. El objetivo es conseguir una reunión. Borrador: '[Mi Borrador de Email]'. Formato de salida: Email optimizado y una lista de 3 cambios clave realizados.", cuandoUsar: "Cold Email", tiempoEstimado: "20 min" },
                    { id: 17, title: "Calendario Instagram 7 Días", prompt: "Crea un 'Calendario de Contenido' para Instagram de 7 días. El contenido debe seguir la estructura: 2 posts de Valor, 2 posts de Venta Suave, 2 posts de Interacción, 1 post Personal. Para cada día, especifica el 'Tipo de Post' (Carrusel, Reel, Historia), el 'Tema' y el 'Objetivo'. Formato de salida: Tabla Markdown.", cuandoUsar: "Redes Sociales", tiempoEstimado: "30 min" },
                    { id: 18, title: "Metáforas para Clientes", prompt: "Soy un desarrollador web. Genera 5 'Metáforas o Analogías' poderosas para explicar el valor de mi servicio de '[Mi Servicio Complejo, ej: Migración a Headless CMS]' a un cliente no técnico. Las metáforas deben ser fáciles de entender y memorables. Formato de salida: Lista numerada de Metáfora y Explicación Breve.", cuandoUsar: "Ventas", tiempoEstimado: "20 min" },
                    { id: 19, title: "Diseño Lead Magnet", prompt: "Diseña un 'Lead Magnet' (Imán de Prospectos) de alto valor para atraer a mi Cliente Ideal. Propón el 'Tema', el 'Formato' (ej: Ebook, Plantilla, Auditoría Gratuita) y el 'Titular de la Landing Page' para descargarlo. El Lead Magnet debe estar directamente relacionado con mi servicio de '[Mi Servicio]'. Formato de salida: Ficha de Lead Magnet.", cuandoUsar: "Captación Leads", tiempoEstimado: "40 min" },
                    { id: 20, title: "Mejora de CTA (CRO)", prompt: "Actúa como un 'Experto en Optimización de Conversión (CRO)'. Analiza la siguiente 'Llamada a la Acción' (CTA) y dame 3 alternativas que aumenten la tasa de conversión. CTA actual: '[Mi CTA Actual]'. Las alternativas deben variar en 'Urgencia', 'Claridad' y 'Beneficio'. Formato de salida: Lista numerada de 3 CTAs Alternativos con su Enfoque.", cuandoUsar: "Optimización Web", tiempoEstimado: "20 min" }
                ]
            }
        ]
    },
    {
        title: "⚡ Automatización",
        color: "bg-yellow-500",
        iconName: "Zap",
        subcategories: [
            {
                title: "Flujos de Trabajo",
                prompts: [
                    { id: 21, title: "Flujo Zapier/Make", prompt: "Eres un 'Ingeniero de Automatización'. Describe un flujo de trabajo de 4 pasos para automatizar la 'Captura de Leads y Envío de Primer Email' utilizando herramientas como Zapier/Make.com. Especifica el 'Disparador' (Trigger), las 'Acciones' en cada paso y el 'Resultado Esperado'. Formato de salida: Diagrama de Flujo de Trabajo en texto.", cuandoUsar: "Automatización", tiempoEstimado: "40 min" },
                    { id: 22, title: "Lógica Script Reportes", prompt: "Genera un 'Script de Python' (solo pseudocódigo o descripción de lógica) para automatizar la 'Generación de Informes Mensuales' de mis proyectos. El script debe tomar datos de una hoja de cálculo (simulada) y generar un resumen ejecutivo en formato Markdown. Describe las 'Funciones Clave' y la 'Lógica de Procesamiento'. Formato de salida: Descripción de Lógica de Script.", cuandoUsar: "Productividad", tiempoEstimado: "50 min" },
                    { id: 23, title: "Sistema Triage Emails", prompt: "Diseña un 'Sistema de Triage de Emails' para mi bandeja de entrada freelance. Define 5 'Reglas de Filtrado' (ej: Cliente Existente, Prospecto Nuevo, Facturación, Spam) y la 'Acción de Automatización' asociada (ej: Etiquetar, Mover a Carpeta, Responder con Plantilla). Formato de salida: Tabla Markdown.", cuandoUsar: "Gestión Email", tiempoEstimado: "30 min" },
                    { id: 24, title: "Plantilla Gestión Proyectos", prompt: "Actúa como un 'Consultor de Productividad'. Propón una 'Plantilla de Trello/Notion' para la gestión de un proyecto freelance de '[Tipo de Proyecto]'. La plantilla debe incluir 5 'Columnas Clave' (Etapas del Proyecto) y 3 'Checklists Estándar' por tarjeta (Tarea). Formato de salida: Estructura de Plantilla (Columnas y Checklists).", cuandoUsar: "Organización", tiempoEstimado: "30 min" },
                    { id: 25, title: "Prompt Resumen Reuniones", prompt: "Crea un 'Prompt Maestro' para una IA que se encargue de 'Resumir Reuniones de 1 Hora' (basado en una transcripción de texto). El prompt debe instruir a la IA a extraer: 3 'Decisiones Clave', 5 'Tareas Asignadas' (con responsable) y 1 'Próximo Paso'. Formato de salida: Prompt Maestro para Resumen de Reunión.", cuandoUsar: "Post-reunión", tiempoEstimado: "15 min" },
                    { id: 26, title: "Flujo Revisión Contenido", prompt: "Soy un redactor. Necesito automatizar la 'Revisión de Tono y Gramática' de mis textos. Sugiere una combinación de 3 herramientas de IA (ej: Grammarly, Hemingway, ChatGPT) y describe el 'Flujo de Revisión' paso a paso. Formato de salida: Flujo de Revisión de Contenido.", cuandoUsar: "Control Calidad", tiempoEstimado: "20 min" },
                    { id: 27, title: "Multi-formato Social", prompt: "Genera un 'Prompt de IA' para 'Crear 10 Variaciones de un Mismo Post' (para diferentes plataformas: Twitter, Instagram Caption, LinkedIn). El prompt debe tomar como entrada el 'Mensaje Central' y especificar las 'Restricciones de Formato' para cada plataforma. Mensaje Central: '[Mi Mensaje Central]'. Formato de salida: Prompt de Generación de Variaciones.", cuandoUsar: "Redes Sociales", tiempoEstimado: "15 min" },
                    { id: 28, title: "Estructura Archivos Digitales", prompt: "Diseña un 'Sistema de Archivo Digital' para mis documentos de proyecto (Contratos, Facturas, Briefs, Entregables). Propón una 'Estructura de Carpetas' jerárquica (máximo 3 niveles) y una 'Convención de Nombres de Archivo' estandarizada. Formato de salida: Estructura de Carpetas y Convención de Nombres.", cuandoUsar: "Organización", tiempoEstimado: "25 min" },
                    { id: 29, title: "Matriz Eisenhower", prompt: "Actúa como un 'Especialista en Gestión del Tiempo'. Utiliza la 'Matriz de Eisenhower' (Urgente/Importante) para clasificar 10 tareas típicas de un freelancer (ej: Responder emails, Crear contenido, Facturar, Llamada de ventas). Para cada tarea, sugiere la 'Acción' (Hacer, Delegar, Programar, Eliminar). Formato de salida: Tabla Markdown.", cuandoUsar: "Priorización", tiempoEstimado: "20 min" },
                    { id: 30, title: "Generador de Briefs", prompt: "Crea un 'Prompt de IA' para 'Generar un Brief Creativo' a partir de una conversación de email con un cliente. El prompt debe solicitar a la IA que extraiga: 'Objetivo del Cliente', 'Público Objetivo', 'Tono de Voz' y 'Restricciones Técnicas'. Formato de salida: Prompt para Generación de Brief.", cuandoUsar: "Inicio Proyecto", tiempoEstimado: "15 min" }
                ]
            }
        ]
    },
    {
        title: "🔎 Competencia",
        color: "bg-red-500",
        iconName: "Search",
        subcategories: [
            {
                title: "Inteligencia de Mercado",
                prompts: [
                    { id: 31, title: "Análisis Competencia Directa", prompt: "Actúa como un 'Analista de Inteligencia Competitiva'. Identifica 3 competidores directos de mi servicio de '[Mi Servicio]' que operan en '[Mi Mercado Geográfico]'. Para cada uno, analiza su 'Propuesta de Valor' (qué prometen), su 'Modelo de Precios' (alto, medio, bajo) y su 'Estrategia de Contenido' (dónde publican). Formato de salida: Tabla Markdown.", cuandoUsar: "Investigación", tiempoEstimado: "45 min" },
                    { id: 32, title: "Análisis FODA Personal", prompt: "Utiliza el framework 'Análisis FODA' (Fortalezas, Oportunidades, Debilidades, Amenazas) para evaluar mi posición como freelancer de '[Mi Área]'. Enfócate en las 'Oportunidades' que la IA ha creado y las 'Amenazas' que representa la automatización. Formato de salida: Ficha FODA estructurada.", cuandoUsar: "Estrategia", tiempoEstimado: "30 min" },
                    { id: 33, title: "Detección de Tendencias", prompt: "Eres un 'Experto en Tendencias'. Identifica 3 'Tendencias de Mercado' (tecnológicas, sociales o económicas) que impactarán mi nicho de '[Mi Nicho]' en los próximos 12 meses. Para cada tendencia, sugiere una 'Acción Proactiva' que debo tomar para capitalizarla. Formato de salida: Lista numerada de Tendencia y Acción Proactiva.", cuandoUsar: "Innovación", tiempoEstimado: "30 min" },
                    { id: 34, title: "Preguntas Cualificación", prompt: "Genera 5 'Preguntas Clave' que debo hacer a un prospecto durante la primera llamada de descubrimiento para entender si es un 'Cliente Ideal' o una 'Pérdida de Tiempo'. Las preguntas deben ser de alto valor y revelar el 'Presupuesto' y la 'Urgencia' de forma indirecta. Formato de salida: Lista numerada de 5 Preguntas Clave.", cuandoUsar: "Ventas", tiempoEstimado: "20 min" },
                    { id: 35, title: "Análisis Reseñas Competencia", prompt: "Diseña un 'Prompt de IA' para 'Analizar 10 Reseñas de Competidores' (simuladas o reales) y extraer los '3 Puntos de Dolor' más comunes y los '3 Puntos Fuertes' más elogiados. El objetivo es encontrar brechas en el mercado. Formato de salida: Prompt de Análisis de Reseñas.", cuandoUsar: "Investigación", tiempoEstimado: "25 min" },
                    { id: 36, title: "Matriz Posicionamiento", prompt: "Actúa como un 'Especialista en Posicionamiento'. Basado en mi 'Valor Único' (definido en prompt 1), crea una 'Matriz de Posicionamiento' de 2x2. Define los 2 ejes (ej: Precio vs. Calidad, Velocidad vs. Personalización) y ubica mi servicio y 3 competidores en la matriz. Formato de salida: Descripción de la Matriz (Ejes y Posiciones).", cuandoUsar: "Marketing", tiempoEstimado: "30 min" },
                    { id: 37, title: "Herramientas IA Competencia", prompt: "Soy un diseñador. Necesito investigar qué 'Herramientas de IA' están usando mis competidores para aumentar su eficiencia. Dame 5 categorías de herramientas (ej: Generación de Imágenes, Prototipado, Gestión de Proyectos) y 2 ejemplos de herramientas por categoría. Formato de salida: Tabla Markdown.", cuandoUsar: "Tecnología", tiempoEstimado: "20 min" },
                    { id: 38, title: "Keywords Cola Larga", prompt: "Crea un 'Prompt de IA' para 'Generar un Reporte de Palabras Clave' de cola larga (long-tail keywords) relacionadas con '[Mi Servicio Específico]' que tengan una intención de 'Compra' o 'Contratación'. El prompt debe solicitar 15 palabras clave. Formato de salida: Prompt para Palabras Clave de Compra.", cuandoUsar: "SEO", tiempoEstimado: "15 min" },
                    { id: 39, title: "Contra-Propuesta Estratégica", prompt: "Analiza la 'Propuesta de Valor' de un competidor (simulada: '[Propuesta del Competidor]') y genera una 'Respuesta Estratégica' que resalte mis ventajas sin menospreciar al competidor. La respuesta debe ser profesional y enfocarse en la 'Diferencia de Resultados'. Formato de salida: Respuesta Estratégica.", cuandoUsar: "Ventas", tiempoEstimado: "30 min" },
                    { id: 40, title: "Hipótesis Freelancer vs Agencia", prompt: "Genera 5 'Hipótesis de Mercado' sobre por qué los clientes eligen a un freelancer en lugar de una agencia para proyectos de '[Mi Tipo de Proyecto]'. Las hipótesis deben ser comprobables y enfocarse en 'Costo', 'Flexibilidad' y 'Atención Personalizada'. Formato de salida: Lista numerada de 5 Hipótesis.", cuandoUsar: "Argumentario Ventas", tiempoEstimado: "25 min" }
                ]
            }
        ]
    },
    {
        title: "⚖️ Legal y Contratos",
        color: "bg-slate-500",
        iconName: "Shield",
        subcategories: [
            {
                title: "Gestión Contractual",
                prompts: [
                    { id: 41, title: "Protección Propiedad Intelectual", prompt: "Actúa como un 'Abogado de Contratos Freelance'. Revisa la siguiente cláusula de 'Propiedad Intelectual' y dame 3 sugerencias para proteger mejor mis derechos como creador de '[Mi Servicio]'. Cláusula: '[Cláusula Actual]'. Formato de salida: Lista numerada de 3 Sugerencias de Protección.", cuandoUsar: "Contratos", tiempoEstimado: "30 min" },
                    { id: 42, title: "Script Defensa Precios", prompt: "Eres un 'Negociador Profesional'. Un cliente me ha solicitado un descuento del 20% en mi tarifa de '[Mi Tarifa]'. Genera un 'Script de Respuesta' que rechace el descuento pero ofrezca una 'Alternativa de Valor' (ej: reducir el alcance, añadir un bono) para mantener la rentabilidad. Formato de salida: Script de Negociación.", cuandoUsar: "Negociación", tiempoEstimado: "20 min" },
                    { id: 43, title: "Cláusula Scope Creep", prompt: "Diseña una 'Cláusula de Alcance del Proyecto' (Scope Creep) para mi contrato. La cláusula debe definir claramente qué constituye un 'Cambio de Alcance', el 'Proceso de Solicitud de Cambio' y la 'Tarifa Adicional' asociada. Formato de salida: Cláusula de Contrato (Texto Legal).", cuandoUsar: "Contratos", tiempoEstimado: "25 min" },
                    { id: 44, title: "Email Seguimiento Propuesta", prompt: "Genera un 'Email de Seguimiento' para un cliente que ha dejado de responder después de recibir mi propuesta. El email debe ser profesional, no acusatorio, y ofrecer 2 'Puntos de Salida' (ej: ¿El proyecto se pospuso? ¿El presupuesto cambió?). Formato de salida: Email de Seguimiento.", cuandoUsar: "Ventas", tiempoEstimado: "15 min" },
                    { id: 45, title: "Resolución Conflictos", prompt: "Actúa como un 'Mediador de Conflictos'. Un cliente está insatisfecho con '[Mi Entregable]' y exige una revisión completa fuera del alcance acordado. Genera un 'Plan de 3 Pasos' para resolver el conflicto de manera profesional, manteniendo la relación y cobrando por el trabajo extra. Formato de salida: Plan de Resolución de Conflictos.", cuandoUsar: "Gestión Cliente", tiempoEstimado: "30 min" },
                    { id: 46, title: "Resumen Ejecutivo Contrato", prompt: "Crea un 'Prompt de IA' para 'Generar un Resumen Ejecutivo' de un contrato de 10 páginas (simulado). El resumen debe destacar: 'Monto Total', 'Plazos de Pago', 'Entregables Clave' y 'Cláusula de Terminación'. Formato de salida: Prompt para Resumen de Contrato.", cuandoUsar: "Administración", tiempoEstimado: "15 min" },
                    { id: 47, title: "Diseño Política Pagos", prompt: "Diseña una 'Política de Pagos' clara para mi negocio freelance. Debe incluir: 'Condiciones de Pago' (ej: 50% inicial), 'Métodos Aceptados', 'Cargos por Pagos Tardíos' y 'Proceso de Facturación'. Formato de salida: Política de Pagos Estructurada.", cuandoUsar: "Finanzas", tiempoEstimado: "30 min" },
                    { id: 48, title: "Terminación Cliente Tóxico", prompt: "Eres un 'Experto en Comunicación Asertiva'. Escribe un 'Email de Terminación de Contrato' (por mi parte) con un cliente tóxico. El email debe ser breve, profesional, citar la 'Cláusula de Terminación' y ofrecer una 'Transición Suave' de los archivos. Formato de salida: Email de Terminación.", cuandoUsar: "Gestión Crisis", tiempoEstimado: "20 min" },
                    { id: 49, title: "Justificación Tarifa Premium", prompt: "Genera 5 'Preguntas de Negociación' que puedo usar para justificar mi tarifa premium de '[Mi Tarifa]' a un cliente que solo pregunta por el precio. Las preguntas deben reorientar la conversación hacia el 'Valor' y el 'Retorno de Inversión' (ROI). Formato de salida: Lista numerada de 5 Preguntas de Valor.", cuandoUsar: "Ventas", tiempoEstimado: "20 min" },
                    { id: 50, title: "Revisión Coherencia Contrato", prompt: "Crea un 'Prompt de IA' para 'Revisar la Coherencia' de un contrato. El prompt debe buscar inconsistencias entre la 'Descripción del Servicio' y los 'Entregables' listados. Formato de salida: Prompt de Revisión de Coherencia de Contrato.", cuandoUsar: "Legal", tiempoEstimado: "15 min" }
                ]
            }
        ]
    },
    {
        title: "🎓 Aprendizaje",
        color: "bg-teal-600",
        iconName: "Book",
        subcategories: [
            {
                title: "Desarrollo Profesional",
                prompts: [
                    { id: 51, title: "Plan de Estudio 4 Semanas", prompt: "Actúa como un 'Mentor de Carrera'. Quiero aprender '[Nueva Habilidad Técnica, ej: Next.js, Drizzle ORM]'. Diseña un 'Plan de Estudio de 4 Semanas' (10 horas/semana). Para cada semana, especifica el 'Módulo de Aprendizaje', los 'Recursos Clave' (ej: Documentación, Tutorial) y un 'Proyecto Práctico' a completar. Formato de salida: Plan de Estudio Semanal.", cuandoUsar: "Upskilling", tiempoEstimado: "40 min" },
                    { id: 52, title: "Curación de Recursos", prompt: "Eres un 'Curador de Contenido'. Dame 5 'Newsletters o Blogs' de alta calidad (en español o inglés) que se centren en '[Mi Nicho]' y que me ayuden a mantenerme actualizado sobre tendencias y herramientas de IA. Formato de salida: Lista numerada de Nombre y Enfoque.", cuandoUsar: "Investigación", tiempoEstimado: "20 min" },
                    { id: 53, title: "Simulador Examen Certificación", prompt: "Diseña un 'Prompt de IA' para 'Simular un Examen de Certificación' sobre '[Mi Área de Experiencia, ej: Google Analytics 4]'. El prompt debe pedir a la IA que genere 10 preguntas de opción múltiple de dificultad media-alta y que proporcione la respuesta correcta con una explicación detallada. Formato de salida: Prompt para Examen de Simulación.", cuandoUsar: "Estudio", tiempoEstimado: "15 min" },
                    { id: 54, title: "Entrenamiento Soft Skills", prompt: "Actúa como un 'Entrenador de Habilidades Blandas'. Quiero mejorar mi habilidad de '[Habilidad Blanda, ej: Escucha Activa en Llamadas de Venta]'. Dame 3 'Ejercicios Prácticos' que pueda realizar esta semana y 3 'Frases Clave' que debo usar para demostrar esta habilidad. Formato de salida: Ejercicios y Frases Clave.", cuandoUsar: "Desarrollo Personal", tiempoEstimado: "30 min" },
                    { id: 55, title: "Explicación Concepto Complejo", prompt: "Genera un 'Prompt de IA' para 'Explicar un Concepto Técnico Complejo' (ej: Arquitectura Serverless) en 3 niveles de dificultad: Nivel 1 (Principiante), Nivel 2 (Intermedio), Nivel 3 (Experto). El objetivo es usar la IA como herramienta de enseñanza. Formato de salida: Prompt de Explicación Multinivel.", cuandoUsar: "Docencia/Estudio", tiempoEstimado: "15 min" },
                    { id: 56, title: "Plan Lectura Libros", prompt: "Soy un freelancer. Necesito un 'Plan de Lectura' de 5 libros (simulados o reales) sobre 'Psicología del Consumidor' aplicado a servicios freelance. Para cada libro, dame el 'Título', el 'Autor' y el 'Concepto Clave' que debo aplicar a mi negocio. Formato de salida: Tabla Markdown.", cuandoUsar: "Formación", tiempoEstimado: "20 min" },
                    { id: 57, title: "Análisis Estilo Escritura", prompt: "Crea un 'Prompt de IA' para 'Analizar mi Estilo de Escritura' (basado en un texto de entrada) y sugerir 3 'Áreas de Mejora' (ej: Uso de voz pasiva, Claridad, Tono) y 3 'Autores de Referencia' cuyo estilo debería estudiar. Formato de salida: Prompt de Análisis de Estilo.", cuandoUsar: "Redacción", tiempoEstimado: "15 min" },
                    { id: 58, title: "Sistema Feedback 360", prompt: "Diseña un 'Sistema de Feedback 360' para mi trabajo. Propón 5 'Preguntas Clave' que debo hacer a mis clientes, 5 a mis colaboradores y 5 a mí mismo para evaluar mi desempeño en el último trimestre. Formato de salida: Lista de Preguntas por Audiencia.", cuandoUsar: "Evaluación", tiempoEstimado: "30 min" },
                    { id: 59, title: "Nuevas Funcionalidades IA", prompt: "Actúa como un 'Especialista en IA'. Dame 3 'Nuevas Funcionalidades de IA' (ej: RAG, Agentes Autónomos, Modelos Multimodales) que, si las aprendo, me darán una ventaja competitiva en mi servicio de '[Mi Servicio]'. Para cada una, sugiere un 'Caso de Uso' específico. Formato de salida: Lista numerada de Funcionalidad y Caso de Uso.", cuandoUsar: "Innovación", tiempoEstimado: "30 min" },
                    { id: 60, title: "Prompt Resumen Podcast", prompt: "Genera un 'Prompt de IA' para 'Crear un Resumen de 5 Puntos' de un podcast de 45 minutos (basado en una transcripción simulada). El resumen debe enfocarse en 'Acciones Prácticas' que puedo implementar inmediatamente. Formato de salida: Prompt para Resumen de Podcast.", cuandoUsar: "Productividad", tiempoEstimado: "15 min" }
                ]
            }
        ]
    },
    {
        title: "🎨 Portafolio",
        color: "bg-pink-600",
        iconName: "User",
        subcategories: [
            {
                title: "Marca Personal",
                prompts: [
                    { id: 61, title: "Optimización Titular LinkedIn", prompt: "Actúa como un 'Especialista en Branding Personal de LinkedIn'. Optimiza mi 'Titular de Perfil' (Headline) actual: '[Mi Titular Actual]'. El nuevo titular debe incluir: Mi Nicho, Mi Valor Único y un Resultado Cuantificable. Máximo 120 caracteres. Formato de salida: 3 Opciones de Titular Optimizadas.", cuandoUsar: "Perfil Social", tiempoEstimado: "20 min" },
                    { id: 62, title: "Reescritura 'Acerca de'", prompt: "Eres un 'Copywriter de Alto Impacto'. Reescribe la sección 'Acerca de' de mi perfil de LinkedIn (basada en el siguiente borrador: '[Mi Borrador de Acerca de]') utilizando una estructura de 'Problema-Solución-Resultado' y enfocándote en el beneficio para el cliente. Formato de salida: Texto de 'Acerca de' optimizado.", cuandoUsar: "Branding", tiempoEstimado: "30 min" },
                    { id: 63, title: "Estrategia Contenido LinkedIn", prompt: "Diseña una 'Estrategia de Contenido de 5 Pilares' para mi LinkedIn. Los pilares deben ser: 1. Casos de Estudio, 2. Opinión de Tendencias, 3. Consejos Prácticos, 4. Detrás de Escena, 5. Interacción. Para cada pilar, dame 2 ideas de post específicas. Formato de salida: Tabla Markdown.", cuandoUsar: "Redes Sociales", tiempoEstimado: "45 min" },
                    { id: 64, title: "Descripción Caso de Estudio", prompt: "Genera un 'Prompt de IA' para 'Crear una Descripción de Proyecto de Portafolio' (Case Study). El prompt debe instruir a la IA a usar la estructura 'Desafío-Solución-Resultados' y a cuantificar el impacto (ej: Aumento de X%, Reducción de Y). Formato de salida: Prompt para Descripción de Caso de Estudio.", cuandoUsar: "Portafolio", tiempoEstimado: "15 min" },
                    { id: 65, title: "Habilidades IA en Demanda", prompt: "Actúa como un 'Reclutador Senior'. Analiza mi lista de 'Habilidades' y sugiere 5 'Habilidades de IA' (ej: Prompt Engineering, Uso de Midjourney, Integración de APIs de LLM) que debo añadir para ser más atractivo en el mercado de '[Mi Nicho]'. Formato de salida: Lista numerada de 5 Habilidades de IA.", cuandoUsar: "Carrera", tiempoEstimado: "20 min" },
                    { id: 66, title: "Solicitud de Testimonios", prompt: "Crea un 'Prompt de IA' para 'Generar 5 Solicitudes de Testimonio' (para clientes satisfechos) con diferentes tonos (Formal, Amigable, Directo, Enfocado en Resultados). El objetivo es obtener testimonios variados para mi web. Formato de salida: Prompt para Solicitudes de Testimonio.", cuandoUsar: "Reputación", tiempoEstimado: "15 min" },
                    { id: 67, title: "Estructura Landing Page", prompt: "Diseña la 'Estructura de una Landing Page' para mi servicio de '[Mi Servicio]'. La estructura debe incluir 7 secciones clave (ej: Titular, Prueba Social, Beneficios, CTA) y el 'Objetivo de Conversión' de cada sección. Formato de salida: Estructura de Landing Page.", cuandoUsar: "Web", tiempoEstimado: "45 min" },
                    { id: 68, title: "Script Video LinkedIn", prompt: "Soy un freelancer. Necesito un 'Script de Video Corto' (máximo 60 segundos) para mi perfil de LinkedIn que explique mi 'Propuesta de Valor' de forma concisa y memorable. El script debe tener 3 escenas (Problema, Solución, CTA). Formato de salida: Script de Video (Escena, Diálogo, Acción).", cuandoUsar: "Video Marketing", tiempoEstimado: "30 min" },
                    { id: 69, title: "Ideas Encuestas LinkedIn", prompt: "Genera 5 'Ideas de Publicaciones' para LinkedIn que utilicen el formato de 'Encuesta' para interactuar con mi audiencia y obtener información sobre sus 'Puntos de Dolor' relacionados con '[Mi Servicio]'. Formato de salida: Lista numerada de 5 Ideas de Encuesta (Pregunta y Opciones).", cuandoUsar: "Engagement", tiempoEstimado: "20 min" },
                    { id: 70, title: "Mejora UX Portafolio", prompt: "Actúa como un 'Diseñador UX/UI'. Revisa la 'Navegación' de mi portafolio (simulada: 3 secciones: Inicio, Servicios, Contacto) y sugiere 3 'Mejoras de Usabilidad' para que el cliente encuentre mi CTA de forma más rápida. Formato de salida: 3 Sugerencias de Usabilidad.", cuandoUsar: "Web", tiempoEstimado: "25 min" }
                ]
            }
        ]
    },
    {
        title: "💰 Finanzas",
        color: "bg-emerald-600",
        iconName: "DollarSign",
        subcategories: [
            {
                title: "Gestión Económica",
                prompts: [
                    { id: 71, title: "Gastos Deducibles", prompt: "Actúa como un 'Contador Freelance'. Dame 5 'Gastos Deducibles' comunes para un freelancer de '[Mi Área]' (ej: Software, Formación, Marketing) y 3 'Consejos de Ahorro Fiscal' que puedo implementar este mes. Formato de salida: Lista de Gastos Deducibles y Consejos Fiscales.", cuandoUsar: "Impuestos", tiempoEstimado: "20 min" },
                    { id: 72, title: "Valor Percibido", prompt: "Eres un 'Especialista en Precios Basados en Valor'. Explica el concepto de 'Valor Percibido' a un cliente y genera 3 'Preguntas de Descubrimiento' que me ayuden a justificar un precio premium de '[Mi Precio]' para mi servicio de '[Mi Servicio]'. Formato de salida: Explicación de Valor Percibido y 3 Preguntas.", cuandoUsar: "Ventas", tiempoEstimado: "30 min" },
                    { id: 73, title: "Presupuesto Mensual", prompt: "Diseña una 'Hoja de Cálculo de Presupuesto Mensual' (solo la estructura en texto) para mi negocio freelance. Debe incluir 5 'Categorías de Ingresos' (ej: Proyectos, Retainers, Productos Digitales) y 5 'Categorías de Gastos Fijos' y 'Variables'. Formato de salida: Estructura de Presupuesto (Ingresos y Gastos).", cuandoUsar: "Finanzas Personales", tiempoEstimado: "30 min" },
                    { id: 74, title: "Cálculo Tarifa Hora", prompt: "Genera un 'Prompt de IA' para 'Calcular mi Tarifa por Hora Ideal' (Hourly Rate). El prompt debe tomar como entrada: 'Salario Anual Deseado', 'Días de Vacaciones', 'Días No Facturables' y 'Gastos Operativos Mensuales'. Formato de salida: Prompt para Cálculo de Tarifa por Hora.", cuandoUsar: "Pricing", tiempoEstimado: "15 min" },
                    { id: 75, title: "Estrategia Reinversión", prompt: "Actúa como un 'Asesor de Inversiones'. Propón una 'Estrategia de Reinversión' para el 20% de mis ingresos mensuales. La estrategia debe enfocarse en 3 áreas: 1. Desarrollo de Habilidades, 2. Automatización, 3. Marketing. Para cada área, sugiere una 'Acción Específica'. Formato de salida: Estrategia de Reinversión.", cuandoUsar: "Crecimiento", tiempoEstimado: "30 min" },
                    { id: 76, title: "Análisis Rentabilidad Proyecto", prompt: "Crea un 'Prompt de IA' para 'Analizar la Rentabilidad' de un proyecto (simulado). El prompt debe tomar como entrada: 'Precio Total', 'Horas Invertidas' y 'Costo de Materiales' y calcular el 'Beneficio Neto' y la 'Tarifa por Hora Real'. Formato de salida: Prompt de Análisis de Rentabilidad.", cuandoUsar: "Post-Mortem", tiempoEstimado: "15 min" },
                    { id: 77, title: "Estrategia Retainer", prompt: "Diseña una 'Estrategia de Retainer' (Iguala Mensual) para mi servicio de '[Mi Servicio]'. Propón 3 'Niveles de Retainer' (Básico, Pro, Premium) con sus respectivos 'Entregables Clave' y 'Precios Sugeridos'. Formato de salida: Tabla de Niveles de Retainer.", cuandoUsar: "Modelo Negocio", tiempoEstimado: "45 min" },
                    { id: 78, title: "Email Aumento Tarifa", prompt: "Eres un 'Experto en Comunicación Financiera'. Escribe un 'Email de Aumento de Tarifa' para un cliente existente. El email debe justificar el aumento (ej: por experiencia, por inflación, por valor añadido) y ser enviado con 30 días de antelación. Formato de salida: Email de Aumento de Tarifa.", cuandoUsar: "Gestión Clientes", tiempoEstimado: "20 min" },
                    { id: 79, title: "Reencuadre Objeciones Precio", prompt: "Genera 5 'Objeciones de Precio' comunes que escucharé para mi servicio de '[Mi Servicio Premium]' y una 'Respuesta de Reencuadre' (Reframing) para cada una, enfocada en el ROI. Formato de salida: Tabla Markdown de Objeción y Respuesta de Reencuadre.", cuandoUsar: "Ventas", tiempoEstimado: "30 min" },
                    { id: 80, title: "Factura Proforma Internacional", prompt: "Crea un 'Prompt de IA' para 'Generar una Factura Proforma' (solo la estructura en texto) para un cliente internacional. La factura debe incluir: 'Datos Fiscales', 'Descripción Detallada del Servicio', 'Moneda', 'Tipo de Cambio' (simulado) y 'Condiciones de Pago Internacional'. Formato de salida: Prompt para Factura Proforma.", cuandoUsar: "Administración", tiempoEstimado: "15 min" }
                ]
            }
        ]
    },
    {
        title: "❤️ Feedback y Mejora",
        color: "bg-orange-500",
        iconName: "MessageCircle",
        subcategories: [
            {
                title: "Calidad y Retención",
                prompts: [
                    { id: 81, title: "Cuestionario Satisfacción", prompt: "Actúa como un 'Diseñador de Encuestas'. Crea un 'Cuestionario de Satisfacción del Cliente' de 5 preguntas (escala Likert y abiertas) para enviar al finalizar un proyecto de '[Mi Tipo de Proyecto]'. Las preguntas deben enfocarse en 'Calidad del Entregable', 'Comunicación' y 'Probabilidad de Recomendación'. Formato de salida: Cuestionario de Satisfacción.", cuandoUsar: "Cierre Proyecto", tiempoEstimado: "20 min" },
                    { id: 82, title: "Análisis Feedback Clientes", prompt: "Eres un 'Analista de Datos'. Genera un 'Prompt de IA' para 'Analizar el Feedback de 10 Clientes' (simulado: '[Lista de Feedback]') y extraer el 'Punto de Dolor Común' y la 'Oportunidad de Nuevo Servicio' más mencionada. Formato de salida: Prompt de Análisis de Feedback.", cuandoUsar: "Investigación", tiempoEstimado: "15 min" },
                    { id: 83, title: "Flujo Onboarding", prompt: "Diseña un 'Flujo de Onboarding de Cliente' de 4 pasos para mi servicio de '[Mi Servicio]'. El flujo debe asegurar que el cliente esté 'Alineado', 'Motivado' y 'Comprometido' con el proceso. Para cada paso, sugiere una 'Acción Clave' (ej: Documento, Llamada, Herramienta). Formato de salida: Flujo de Onboarding.", cuandoUsar: "Procesos", tiempoEstimado: "40 min" },
                    { id: 84, title: "Entrevista Cliente Perdido", prompt: "Genera 5 'Preguntas de Entrevista' para un 'Cliente Perdido' (Lost Client) que me ayuden a entender por qué eligió a la competencia. Las preguntas deben ser respetuosas y enfocarse en 'Valor', 'Precio' y 'Proceso'. Formato de salida: Lista numerada de 5 Preguntas a Cliente Perdido.", cuandoUsar: "Mejora Continua", tiempoEstimado: "20 min" },
                    { id: 85, title: "Momentos WOW", prompt: "Actúa como un 'Especialista en Experiencia del Cliente (CX)'. Propón 3 'Momentos WOW' (pequeños detalles inesperados) que puedo añadir a mi proceso de servicio para deleitar a mis clientes y fomentar el boca a boca. Formato de salida: Lista numerada de 3 Momentos WOW.", cuandoUsar: "Fidelización", tiempoEstimado: "30 min" },
                    { id: 86, title: "Ajuste Propuesta Valor", prompt: "Crea un 'Prompt de IA' para 'Revisar mi Propuesta de Valor' (basada en el feedback de clientes) y sugerir 3 'Ajustes de Lenguaje' para que resuene más con sus necesidades reales. Formato de salida: Prompt de Ajuste de Propuesta de Valor.", cuandoUsar: "Marketing", tiempoEstimado: "15 min" },
                    { id: 87, title: "Email Cierre y Testimonio", prompt: "Diseña una 'Plantilla de Email de Cierre de Proyecto' que solicite 'Feedback', 'Testimonio' y 'Referencia' de forma profesional y no invasiva. Formato de salida: Plantilla de Email de Cierre.", cuandoUsar: "Gestión Clientes", tiempoEstimado: "15 min" },
                    { id: 88, title: "Análisis Cuellos de Botella", prompt: "Eres un 'Consultor de Procesos'. Analiza mi proceso de trabajo (simulado: '[Mi Proceso Actual]') e identifica 3 'Cuellos de Botella' (Bottlenecks) y sugiere una 'Solución de Automatización' para cada uno. Formato de salida: Cuellos de Botella y Soluciones.", cuandoUsar: "Eficiencia", tiempoEstimado: "40 min" },
                    { id: 89, title: "KPIs Negocio Freelance", prompt: "Genera 5 'Indicadores Clave de Rendimiento' (KPIs) para medir el éxito de mi negocio freelance (más allá de los ingresos). Los KPIs deben enfocarse en 'Satisfacción', 'Eficiencia' y 'Crecimiento'. Formato de salida: Lista numerada de 5 KPIs.", cuandoUsar: "Gestión", tiempoEstimado: "20 min" },
                    { id: 90, title: "Estrategia Follow-up", prompt: "Actúa como un 'Especialista en Retención de Clientes'. Propón 3 'Estrategias de Follow-up' (Seguimiento) para clientes que terminaron un proyecto hace 6 meses, con el objetivo de ofrecerles un nuevo servicio o retainer. Formato de salida: 3 Estrategias de Follow-up.", cuandoUsar: "Ventas", tiempoEstimado: "30 min" }
                ]
            }
        ]
    },
    {
        title: "🚀 Ventas Avanzadas",
        color: "bg-indigo-600",
        iconName: "Briefcase",
        subcategories: [
            {
                title: "Materiales de Conversión",
                prompts: [
                    { id: 91, title: "Estructura Webinar Venta", prompt: "Actúa como un 'Guionista de Webinars'. Diseña la 'Estructura de un Webinar de 45 Minutos' para vender mi servicio de '[Mi Servicio]'. La estructura debe incluir: 10 min de Valoración, 25 min de Contenido de Alto Valor (con un 'Secreto' revelado) y 10 min de 'Oferta Irresistible' (con escasez y urgencia). Formato de salida: Estructura de Webinar (Tiempo, Contenido, Objetivo).", cuandoUsar: "Lanzamientos", tiempoEstimado: "60 min" },
                    { id: 92, title: "Storytelling Casos Éxito", prompt: "Eres un 'Experto en Storytelling'. Genera 3 'Historias de Clientes' (simuladas) para usar en un Case Study. Cada historia debe seguir la estructura: 'Antes' (Desafío), 'Durante' (Mi Solución) y 'Después' (Resultado Cuantificable). Formato de salida: 3 Historias de Clientes.", cuandoUsar: "Portafolio", tiempoEstimado: "45 min" },
                    { id: 93, title: "Títulos Ebook Lead Magnet", prompt: "Crea un 'Prompt de IA' para 'Generar 5 Títulos de Ebook' (para un Lead Magnet avanzado) sobre '[Mi Tema de Experiencia]'. Los títulos deben ser aspiracionales y prometer una transformación. Formato de salida: Prompt para Títulos de Ebook.", cuandoUsar: "Marketing", tiempoEstimado: "15 min" },
                    { id: 94, title: "Estructura Pitch Deck", prompt: "Diseña una 'Estructura de Presentación de Ventas' (Pitch Deck) de 10 diapositivas para una reunión con un cliente corporativo. La estructura debe incluir: Problema, Solución, Mi Valor Único, Casos de Éxito, Equipo (Yo), Inversión y Próximos Pasos. Formato de salida: Estructura de Pitch Deck (Diapositiva y Contenido Clave).", cuandoUsar: "Reunión Ventas", tiempoEstimado: "45 min" },
                    { id: 95, title: "Preguntas Formulario", prompt: "Genera 5 'Preguntas de Calificación' para usar en un formulario de 'Solicitud de Propuesta' en mi web. Las preguntas deben filtrar a los clientes que no tienen el 'Presupuesto' o la 'Alineación de Valores' adecuada. Formato de salida: Lista numerada de 5 Preguntas de Calificación.", cuandoUsar: "Filtrado Leads", tiempoEstimado: "20 min" },
                    { id: 96, title: "Copy Sección Precios", prompt: "Actúa como un 'Redactor de Landing Pages'. Escribe el 'Copy para la Sección de Precios' de mi web. El copy debe justificar la inversión y usar la técnica de 'Anclaje de Precios' (mostrando un precio más alto primero). Formato de salida: Copy de Sección de Precios.", cuandoUsar: "Web", tiempoEstimado: "30 min" },
                    { id: 97, title: "Generador FAQ Objeciones", prompt: "Crea un 'Prompt de IA' para 'Generar 10 Preguntas Frecuentes' (FAQ) sobre mi servicio de '[Mi Servicio]' que aborden las objeciones más comunes (Precio, Tiempo, Riesgo). Formato de salida: Prompt para Preguntas Frecuentes.", cuandoUsar: "Web/Ventas", tiempoEstimado: "15 min" },
                    { id: 98, title: "Secuencia Email Post-Webinar", prompt: "Diseña un 'Email de Follow-up Post-Webinar' de 3 partes. El email 1 debe ser de 'Agradecimiento y Grabación', el email 2 de 'Valor Adicional y Testimonio' y el email 3 de 'Oferta Final y Urgencia'. Formato de salida: Estructura de Secuencia de Emails.", cuandoUsar: "Email Marketing", tiempoEstimado: "40 min" },
                    { id: 99, title: "Optimización Testimonio", prompt: "Eres un 'Experto en Testimonios'. Revisa el siguiente testimonio y reescríbelo para que sea más 'Específico', 'Creíble' y 'Orientado a Resultados'. Testimonio: '[Mi Testimonio Actual]'. Formato de salida: Testimonio Optimizado.", cuandoUsar: "Web", tiempoEstimado: "20 min" },
                    { id: 100, title: "Resumen Social Proof", prompt: "Genera un 'Prompt de IA' para 'Crear un Resumen de 1 Párrafo' de mi Case Study más exitoso. El resumen debe ser ideal para usar como 'Prueba Social' en mi página de inicio. Formato de salida: Prompt para Resumen de Prueba Social.", cuandoUsar: "Web", tiempoEstimado: "15 min" }
                ]
            }
        ]
    }
];
